version: '3'

services:
  confd-app:
    container_name: confd-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: "no"
    environment:
      MYSQL_HOST: ${MYSQL_HOST:-mysql}
      MYSQL_PORT: ${MYSQL_PORT:-3306}
      MYSQL_USER: ${MYSQL_USER:-root}
      MYSQL_PASS: ${MYSQL_PASS:-admin}
    networks:
      - netlocal
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:5.7.22
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 33006:3306
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS:-admin}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-TEST_DATABASE}
    networks:
      - netlocal

networks:
  netlocal:
    driver: bridge
